CREATE TABLE `dmc_micro_service` (
  `id` bigint(20) NOT NULL,
  `service_name` varchar(32) CHARACTER SET utf8 DEFAULT NULL COMMENT '服务名称',
  `route_name` varchar(200) CHARACTER SET utf8 DEFAULT NULL COMMENT '路由别名',
  `route_prefix` varchar(200) CHARACTER SET utf8 DEFAULT NULL COMMENT '路由前缀',
  `client_id` varchar(200) CHARACTER SET utf8 DEFAULT NULL COMMENT '服务标示',
  `client_secret` varchar(200) CHARACTER SET utf8 DEFAULT NULL COMMENT '服务密钥',
  `type` int(11) DEFAULT '0' COMMENT '服务类型 自系统/异系统',
  `base_url` varchar(200) CHARACTER SET utf8 DEFAULT NULL COMMENT '服务基础地址',
  `status` int(11) DEFAULT '0' COMMENT '状态',
  `remark` varchar(300) DEFAULT NULL COMMENT '描述',
  `icon` varchar(50) DEFAULT NULL,
  `picture` varchar(200) DEFAULT NULL,
  `sort` int(11) DEFAULT NULL,
  `contacter` varchar(50) DEFAULT NULL COMMENT '联系人',
  `mobile` varchar(15) DEFAULT NULL COMMENT '手机号',
  `creator` varchar(20) DEFAULT NULL COMMENT '创建人',
  `creator_id` bigint(20) DEFAULT NULL COMMENT '创建人ID',
  `created_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_operator` varchar(20) DEFAULT NULL COMMENT '更新操作人',
  `update_operator_id` bigint(20) DEFAULT NULL COMMENT '更新操作人ID',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='微服务应用';
